
name: Deploy to Chrom web store

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run deploy script to build and package the extension
        run: |
          npm install
          npm run deploy
          
      - name: Upload & release
        uses: mnao305/chrome-extension-upload@2.2.0
        with:
          file-path: releases/googlerankchecker.zip
          extension-id: ehgbmeaekkaeajmapeefcolejlaamdip
          client-id: ${{ secrets.CHROME_STORE_CLIENT_ID }}
          refresh-token: ${{ secrets.CHROME_STORE_REFRESH_TOKEN }}
          publish: false


